### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by boomzero**
this is easier.

### CODE REVIEW

**Comment by langningchen** [comment]
Why closed?

**Comment by boomzero** [comment]
> Why closed?

Because your script's TUI doesn't work

**Comment by boomzero** [comment]
In this way

**Comment by boomzero** [comment]
But please test it

**Comment by boomzero** [comment]
If it works then it's a github codespace bug

**Comment by boomzero** [comment]
tr: Illegal byte sequence
tr: Illegal byte sequence

**Comment by langningchen** [comment]
> > Why closed?
> 
> Because your script's TUI doesn't work

Emm, what's TUI...?

**Comment by boomzero** [comment]
> > > Why closed?
> > 
> > 
> > Because your script's TUI doesn't work
> 
> Emm, what's TUI...?

https://en.wikipedia.org/wiki/Text-based_user_interface

**Comment by langningchen** [comment]
Why doesn't it worked?

**Comment by langningchen** [comment]
image

It worked with `cat` and pipe. I can't test curl for the block of `githubusercontent.com`.

**Comment by boomzero** [comment]
> image
> 
> It worked with `cat` and pipe. I can't test curl for the block of `githubusercontent.com`.

input doesn't work

**Comment by boomzero** [comment]
input of data

**Comment by langningchen** [comment]
Ohh, I see

**Pull request closed without merging**
